Dropping MacOS

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -124,103 +124,6 @@ jobs:
           path: ${{ env.harvester_artifact_path }}
           if-no-files-found: error
 
-  build-harvester-macos-x86-64:
-    runs-on: macOS-11
-    steps:
-      - name: Cleanup Environment
-        uses: Chia-Network/actions/clean-workspace@main
-
-      - name: Checkout Repo
-        uses: actions/checkout@v3
-
-      - name: Get Version Number
-        id: version_number
-        shell: bash
-        run: ./.github/actions/get-version.sh macos x86-64
-
-      - name: Install Prerequisites
-        shell: bash
-        run: |
-          set -eo pipefail
-          brew install cmake make git wget
-          echo 'alias sudo=""' >> ~/.bashrc && source ~/.bashrc
-
-      - name: Setup CUDA
-        uses: Jimver/cuda-toolkit@v0.2.10
-        id: cuda-toolkit
-        with:
-          cuda: '12.1.0'
-
-      - name: Verify CUDA
-        shell: bash
-        run: |
-          echo "Installed cuda version is: ${{ steps.cuda-toolkit.outputs.cuda }}"
-          echo "Cuda install location: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
-          nvcc -V
-
-      - name: Build Harvester
-        shell: bash
-        run: |
-          export artifact_name="green_reaper-v${{ env.BB_VERSION }}-macos-x86-64"
-          echo "harvester_artifact_name=${artifact_name}" >> "$GITHUB_ENV"
-          # emits env.harvester_artifact_path
-          bash .github/actions/build-harvester.sh --artifact "${artifact_name}"
-
-      - name: Upload Harvester Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.harvester_artifact_name }}
-          path: ${{ env.harvester_artifact_path }}
-          if-no-files-found: error
-
-  build-harvester-macos-arm64:
-    runs-on: [macOS, ARM64]
-    steps:
-      - name: Cleanup Environment
-        uses: Chia-Network/actions/clean-workspace@main
-
-      - name: Checkout Repo
-        uses: actions/checkout@v3
-
-      - name: Get Version Number
-        id: version_number
-        run: bash -e .github/actions/get-version.sh macos arm64
-
-      - name: Install Prerequisites
-        shell: bash
-        run: |
-          set -eo pipefail
-          brew install cmake make git wget
-          echo 'alias sudo=""' >> ~/.bashrc && source ~/.bashrc
-
-      - name: Setup CUDA
-        uses: Jimver/cuda-toolkit@v0.2.10
-        id: cuda-toolkit
-        with:
-          cuda: '12.1.0'
-
-      - name: Verify CUDA
-        shell: bash
-        run: |
-          echo "Installed cuda version is: ${{ steps.cuda-toolkit.outputs.cuda }}"
-          echo "Cuda install location: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
-          nvcc -V
-
-      - name: Build Harvester
-        shell: bash
-        run: |
-          export artifact_name="green_reaper-v${{ env.BB_VERSION }}-macos-arm64"
-          echo "harvester_artifact_name=${artifact_name}" >> "$GITHUB_ENV"
-          # emits env.harvester_artifact_path
-          bash .github/actions/build-harvester.sh --artifact "${artifact_name}"
-
-      - name: Upload Harvester Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.harvester_artifact_name }}
-          path: ${{ env.harvester_artifact_path }}
-          if-no-files-found: error
-
   build-harvester-windows-x86-64:
     runs-on: windows-2022
     steps:
@@ -557,6 +460,102 @@ jobs:
   #         path: ${{ github.workspace }}/bin/${{ env.BB_ARTIFACT_NAME }}
   #         if-no-files-found: error
 
+  # build-harvester-macos-x86-64:
+  #   runs-on: macOS-11
+  #   steps:
+  #     - name: Cleanup Environment
+  #       uses: Chia-Network/actions/clean-workspace@main
+
+  #     - name: Checkout Repo
+  #       uses: actions/checkout@v3
+
+  #     - name: Get Version Number
+  #       id: version_number
+  #       shell: bash
+  #       run: ./.github/actions/get-version.sh macos x86-64
+
+  #     - name: Install Prerequisites
+  #       shell: bash
+  #       run: |
+  #         set -eo pipefail
+  #         brew install cmake make git wget
+  #         echo 'alias sudo=""' >> ~/.bashrc && source ~/.bashrc
+
+  #     - name: Setup CUDA
+  #       uses: Jimver/cuda-toolkit@v0.2.10
+  #       id: cuda-toolkit
+  #       with:
+  #         cuda: '12.1.0'
+
+  #     - name: Verify CUDA
+  #       shell: bash
+  #       run: |
+  #         echo "Installed cuda version is: ${{ steps.cuda-toolkit.outputs.cuda }}"
+  #         echo "Cuda install location: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
+  #         nvcc -V
+
+  #     - name: Build Harvester
+  #       shell: bash
+  #       run: |
+  #         export artifact_name="green_reaper-v${{ env.BB_VERSION }}-macos-x86-64"
+  #         echo "harvester_artifact_name=${artifact_name}" >> "$GITHUB_ENV"
+  #         # emits env.harvester_artifact_path
+  #         bash .github/actions/build-harvester.sh --artifact "${artifact_name}"
+
+  #     - name: Upload Harvester Artifact
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.harvester_artifact_name }}
+  #         path: ${{ env.harvester_artifact_path }}
+  #         if-no-files-found: error
+
+  # build-harvester-macos-arm64:
+  #   runs-on: [macOS, ARM64]
+  #   steps:
+  #     - name: Cleanup Environment
+  #       uses: Chia-Network/actions/clean-workspace@main
+
+  #     - name: Checkout Repo
+  #       uses: actions/checkout@v3
+
+  #     - name: Get Version Number
+  #       id: version_number
+  #       run: bash -e .github/actions/get-version.sh macos arm64
+
+  #     - name: Install Prerequisites
+  #       shell: bash
+  #       run: |
+  #         set -eo pipefail
+  #         brew install cmake make git wget
+  #         echo 'alias sudo=""' >> ~/.bashrc && source ~/.bashrc
+
+  #     - name: Setup CUDA
+  #       uses: Jimver/cuda-toolkit@v0.2.10
+  #       id: cuda-toolkit
+  #       with:
+  #         cuda: '12.1.0'
+
+  #     - name: Verify CUDA
+  #       shell: bash
+  #       run: |
+  #         echo "Installed cuda version is: ${{ steps.cuda-toolkit.outputs.cuda }}"
+  #         echo "Cuda install location: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
+  #         nvcc -V
+
+  #     - name: Build Harvester
+  #       shell: bash
+  #       run: |
+  #         export artifact_name="green_reaper-v${{ env.BB_VERSION }}-macos-arm64"
+  #         echo "harvester_artifact_name=${artifact_name}" >> "$GITHUB_ENV"
+  #         # emits env.harvester_artifact_path
+  #         bash .github/actions/build-harvester.sh --artifact "${artifact_name}"
+
+  #     - name: Upload Harvester Artifact
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.harvester_artifact_name }}
+  #         path: ${{ env.harvester_artifact_path }}
+  #         if-no-files-found: error
 
 ### Consolidated
 
